### PR TITLE
DSatur algorithm for graph coloring

### PR DESCRIPTION
**Pull request by gbagan**
Hi again,

This PR proposes an implementation of DSatur algorithm to (properly) color a graph.
https://en.wikipedia.org/wiki/DSatur

This is a heuristic with time complexity `O((|V|+ |E|) log |V|)`.

Tests, quickcheck tests and benchmarks have been done.

### CODE REVIEW

**Comment by starovoid** [comment]
Hi, 
Do I understand correctly that help is required in completing this implementation?

I also have a few suggestions:

### 1. Specify the capacities
```rust
let mut degree_map = HashMap::new();
let mut queue =  BinaryHeap::new();
let mut colored = HashMap::new();
let mut adj_color_map = HashMap::new();
let mut seen = graph.visit_map();
```

Specifying capacity during initialization using `::with_capacity(n)` may improve performance, and is also a good tone.

### 2. Remove `.unwrap()`
You can get rid of `.unwrap()` using the syntax `if let ...`. 
I mean the code
```rust
let adj_color = adj_color_map.get_mut(&nbor).unwrap();
adj_color.insert(color);
queue.push(MaxScored((adj_color.len(), degree_map[&nbor]), nbor));
```

**Comment by XVilka** [comment]
@starovoid if you are willing to finish this one, I think it would be a really cool addition to 0.6.6

**Comment by starovoid** [comment]
> @starovoid if you are willing to finish this one, I think it would be a really cool addition to 0.6.6

Yes, I will do it soon.

**Comment by XVilka** [comment]
Superseded by https://github.com/petgraph/petgraph/pull/700

**Pull request closed without merging**
