### PR TITLE
Switch from travis to github actions for CI

### LINKED ISSUE #390: Migrate from Travis CI to GitHub Actions
Currently petgraph uses Travis CI which will stop (if not already stopped) to run for the open source. Switching to GitHub Actions will give more flexibility.

### PR DESCRIPTION
**Pull request by bluss**
Copy setup from matrixmultiply and adapt to do the same test as the old travis test. Also fixes the running of rustfmt (but not fixing the formatting in this PR).

Fixes #390

### CODE REVIEW

**Comment by bluss** [comment]
rustfmt didn't run correctly in previous travis setup. Here it runs, but the format check fails. I've set it to an allowed failure for now - still visible on the PR.

**Review by jrraymond — APPROVED** [review]

**Comment by bluss** [comment]
Thanks

**Comment by bluss** [comment]
As noted - the running of rustfmt is fixed. It's marked wiht "continue-on-error" for rustfmt. Fixing can be a different PR. Existing PRs will need to rebase onto master to get the new github actions CI.

**Comment by bluss** [comment]
I'm integrating this without merge commit - not my preference but I believe that's what @XVilka prefers?

**Comment by XVilka** [comment]
Precisely, thank you!

**Pull request merged**
