### PR TITLE
Add immutable node_weights and edge_weights methods.

### PR DESCRIPTION
**Pull request by mankinskin**

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Comment by Mcat12** [comment]
Can this be merged?

**Comment by mankinskin** [comment]
Can this be merged?

**Review by bluss — COMMENTED** [review]
Lgtm. The comments are suggestions that are not mandatory - but wishes.

it would also be a wish (that we should mention) that new features in Graph like this are accompanied by new graph visitor traits, so that we keep expanding the features of generic graphs.

**Comment by mankinskin** [comment]
Rebased and applied suggestions.

Also fixed a warning in `tests/graph.rs`

**Comment by ABorgna** [comment]
All checks are green and the PR works nicely. I'll just rebase it to double-check the tests before merging.
The lasts commits fixing the rustfmt lint are already in master, so they will be dropped.

**Comment by ABorgna** [comment]
I'm terribly sorry. My push of the rebased commits somehow stopped in the middle, and now I can't push anymore since the PR auto-closed.

Here are your changes in a patch, you can apply them over master (with `git am <patch>`) and I'll reopen the PR.

[immutable_weights.txt](https://github.com/petgraph/petgraph/files/6393742/immutable_weights.txt)

**Comment by mankinskin** [comment]
Sorry, I did not have much time lately.. thanks for resolving this :)

**Pull request closed without merging**
