### PR TITLE
Split out `petgraph` into separate crates

### PR DESCRIPTION
**Pull request by indietyp**
* `visit` deprecated, available in `petgraph-core`
* `data` deprecated, available in `petgraph-core`
* move `IndexType` to `petgraph-core`
* move `EdgeType`, and related to `petgraph-core`
* rework `IndexType` to make use of `funty`

### CODE REVIEW

**Comment by indietyp** [comment]
- `petgraph-core`: ✅ 
- `petgraph-graph`: ✅ 
- `petgraph-graphmap`: ✅ 
- `petgraph-adjacency-list`: ✅ 
- `petgraph-csr`: ❌ 
- `petgraph-algorithms`: ❌ 
- `petgraph-matrix-graph`: ❌ 
- `petgraph-dot`:  ❌ 

Everything compiles with the default feature sets, and all tests pass.

quickcheck + serde: untested
tests haven't been ported to their respective crates just yet
cargo-hack: not run yet, needs `quickcheck` fix for negative cycle first
everything has been converted to `no-std`, where possible, `no-alloc`.
Setting everything to `deprecated` as default will un-deprecate one-by-one after #552 is resolved.

**Comment by indietyp** [comment]
## Progress Report

-    petgraph-core: ✅
-    petgraph-graph: ✅
-    petgraph-graphmap: ✅
-    petgraph-adjacency-matrix: ✅
-    petgraph-csr: ✅ 
-    petgraph-algorithms: ⌛ 
-    petgraph-matrix-graph: ✅ 
-    petgraph-dot: ❌

The algorithms crate is by far the most challenging one; some algorithms require specific graphs (like `Graph` or `AdjacencyMatrix`). Most likely, these imports can be removed, but this will take a bit more time. While rummaging around the insides, I took the liberty of moving `traversal` from `visit` to `petgraph-algorithms`; while doing so, I plan to rework them to modernize them a bit. (The old will stay in core like they are and are deprecated)

**Comment by indietyp** [comment]
## Progress Report

-    petgraph-core: ✅
-    petgraph-graph: ✅
-    petgraph-graphmap: ✅
-    petgraph-adjacency-matrix: ✅
-    petgraph-csr: ✅ 
-    petgraph-algorithms: ✅ 
-    petgraph-matrix-graph: ✅ 
-    ~~petgraph-dot: ❌~~


* All crates have been successfully ported, `serde` has been reworked.
* `dot` still lives in `petgraph` and is now backed by the `dot` crate, I am currently contemplating replacing it in favor of `graphviz-rust`, as it allows serialization and deserialization, in the future we might want to move it into `petgraph-io` 
(or something similar) and also implement other formats, like `GEXF`.
* sadly the `dot` feature now requires `std` as it uses `std::io::Write` :/
* The only thing now remaining are some compile errors I left behind, quickcheck, testing.
	* for `proptest` I was thinking to create a companion `petgraph-proptest`, which implements multiple strategies. Nothing short-term.
* I have decided against reworking the currently non-generic algorithms, as it would be redundant first converting them and then reworking the traits, they are currently gated behind a temporary feature gat.

**Comment by indietyp** [comment]
## Progress Report

* New crates: `petgraph-generators`, `petgraph-proptest`

While trying to upgrade to proptest I noticed that our quicktest is really feasible in quicktest 1.0 and likely also doesn't correctly shrink. I have taken the liberty to transfer to `proptest` and completely reworked the shrinking and generation.

The code is now generic and can easily be implemented for all kinds of graphs as well is configurable, so if users do not like the default, they can just call `default::graph_strategy` from the implementation with their arguments and graph type. With this change, we're likely to also support proptest on all existing types!

Crates compile (again). Due to the very nature of what we're trying to do (separating the concerns, making things more maintainable, etc.), there are quite a handful of new crates; they are now grouped under `crates/` to keep things clean (commit message of [795a994](https://github.com/petgraph/petgraph/pull/561/commits/795a9940932e01b31563f6a3d9a96e527cae1080) mentions inspirations)

The only thing missing are now moving the tests

**Comment by indietyp** [comment]
## Progress Report

quite a lot of tests have been ported; remaining are:

* graph (directed)
* algorithms in directed
* list
* quickcheck (to proptest)
* stable-graph
* graphmap

**Comment by indietyp** [comment]
I know this is quite a large PR 😅. I'll be waiting for any comments until the end of the week (or until I get approval) and then merge them into the `next` branch.

**Comment by theoparis** [comment]
Why isn't this merged into the master branch? The next branch seems out of date and it also fails to build:
```
error[E0107]: struct takes 2 generic arguments but 1 generic argument was supplied
   --> /home/theo/.cargo/git/checkouts/petgraph-452bd86bb1acd2d2/5c8ab66/crates/matrix-graph/src/lib.rs:980:18
    |
980 |     removed_ids: IndexSet<usize>,
    |                  ^^^^^^^^ ----- supplied 1 generic argument
    |                  |
    |                  expected 2 generic arguments
    |
note: struct defined here, with 2 generic parameters: `T`, `S`
   --> /home/theo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.3.0/src/set.rs:88:12
    |
88  | pub struct IndexSet<T, S> {
    |            ^^^^^^^^ -  -
help: add missing generic argument
    |
980 |     removed_ids: IndexSet<usize, S>,
    |                                +++

```

**Comment by indietyp** [comment]
I've been super busy with trying to finish my masters, so finding time for petgraph, in between work, regular university, working on my thesis, and still enjoying some free time has been tough. This is all - at the end of the day - just free OSS volunteer work - which - while I am very stoked (was and still am) to work on it, just tends to fall behind if you have other things to take care of in life.

I reckon that at the latest (hopefully sooner, but no promises), once I have successfully completed my masters, I'll be able to return to the project with new vigor.

**Pull request merged**
