### PR TITLE
Initial scaffolding

### PR DESCRIPTION
**Pull request by indietyp**
This does internal "rejuvination" (outlined under 7 of #551)

# Changes

* raise MSRV to `1.65`
* replace `Makefile` with `just`
	* permutations are tested using `cargo-hack`, tests are run through `nextest`
* `RELEASES.rst` has been converted to `CHANGELOG.md` (to be consistent with the rest of the Rust ecosystem)
	* now adheres to https://keepachangelog.com/en/1.1.0/
* `custom.css` is not properly added to the docs output
* `custom.css` and `graph-example.dot` have been moved to `doc/`
* I have added currently active maintainers in the list of authors
* I have added a `rust-toolchain.toml` and (currently empty) `rustfmt.toml`
	* I'd like to add a bit more of an "opinionated" touch to the `rustfmt.toml`, adding more settings, they are more of personal taste (but I think they improve rustfmt quite a lot), so I haven't applied them just yet. Please let me know if I can/should!
* ci has been revamped, with 3 stages, that use the justfile.
	* currently checks coverage but does _not_ upload it to codecov or similar, we might want to do that in the future.
* added an exhaustive list of clippy lints
* the generated `graph-example.svg` is now part of the repository, CI checks that the output of `dot` matches the current file, and will fail otherwise. This way it is possible for people to depend on the repository directly.

# Questions

What is the following snippet about?

```
[package.metadata.release]
no-dev-version = true
```

Is `package.metadata.docs.rs` needed?

I have gone through the git history and have tagged every release locally. I plan to publish those tags as referenced in the new `CHANGELOG.md` is this okay? Because we plan on publishing multiple libraries, I have adopted the common pattern of `petgraph@v<version>`

### CODE REVIEW

**Comment by indietyp** [comment]
There are a lot of errors in CI right now, so for now, I will disable it for the `next` branch because we expect many things to change. I am not going to bother with lints right now, but will apply them gradually when changing things in the next steps.

**Comment by indietyp** [comment]
it seems like it takes an extraordinarily long time to run a single run (194s); most of that time is spent on quickcheck. I wonder if we'd be able to make this faster by switching to proptest (which in contrast to `quickcheck` seems to be actively maintained), as well as selectively removing features/requiring features. This will need more testing. Even if we switch to proptest, we should still provide quickcheck integration! I think providing for both would be a net benefit.

We also have a high number of test permutations. I think that is because we currently do not use `dep:` dependencies, this will change in upcoming PRs.

Currently, it would take 15 hours to run all tests, and I don't think that's feasible 😅

**Comment by bluss** [comment]
`package.metadata.release` is from cargo-release. If we don't want to use it, then it's not necessary. The docs.rs metadata - yes it's needed so that generated docs contains traits from those features. We can consider using all-features = true instead in the metadata, or cherry-pick features to use.

**Review by bluss — APPROVED** [review]
Looks good to me, nice way to go

**Comment by indietyp** [comment]
I was thinking of using cargo-release anyway, so it's good to know that my suspicions were confirmed!

**Pull request merged**
